version: "3.0"
services:
  frps:
    build: .
    restart: always
    network_mode: host
    command: [
      'frpc',
      '-c',
      '/etc/frpc.toml'
    ]
    volumes:
      - ./frpc.toml:/etc/frpc.toml

